import React, { useState } from 'react';
import "@fontsource/poppins"; // Defaults to weight 400


const LegalStatus = ({ onLegalStatusChange, selectedValue }) => {
    const legalStatus = ["Société d'assurances mutuelles",
        "Société coopérative à responsabilité limitée",
        "Société coopérative de consommation par actions simplifiée",
        "Société civile de placement immobilier à capital variable",
        "Collectivité territoriale de la République",
        "Fondation",
        "Société anonyme à conseil d'administration",
        "Société civile immobilière à capital variable",
        "Société civile professionnelle d'avoués",
        "Société professionnelle à capital variable",
        "Union de sociétés coopératives à responsabilité limitée et capital variable",
        "Société coopérative de banque à forme anonyme et capital variable",
        "Société coopérative à forme anonyme à capital variable",
        "Société anonyme d'un Etat non membre de la CE ou non partie à l'accord sur l'Espace économique européen",
        "Société anonyme à participation ouvrière",
        "Société anonyme d'économie mixte",
        "Société coopérative ouvrière de production à responsabilité limitée à capital variable",
        "Société coopérative ouvrière de production à forme anonyme et capital variable",
        "Société coopérative d'intérêt collectif à forme anonyme à capital variable",
        "Société coopérative d'intérêt collectif d'HLM à forme anonyme",
        "Société coopérative d'intérêt collectif à forme anonyme",
        "Société civile professionnelle de directeurs de laboratoires d'analyses médicales",
        "Société par actions simplifiée  à associé unique et capital variable",
        "Société à responsabilité limitée à capital variable",
        "Société civile professionnelle de géomètres experts",
        "Société civile à capital variable",
        "Société publique locale",
        "Etablissement public de coopération culturelle à caractère industriel et commercial",
        "Coopérative d'utilisation de matériel agricole",
        "Union d'économie sociale - Société coopérative à forme anonyme",
        "Sans correspondance;",
        "Association",
        "Société coopérative de banque populaire à forme anonyme",
        "Société civile coopérative à capital variable",
        "Société coopérative de production d'HLM à forme anonyme",
        "Société coopérative ouvrière de production à forme anonyme",
        "Société coopérative de travailleurs à forme anonyme",
        "Etablissement public étranger",
        "Groupement d'intérêt public",
        "Mutuelle",
        "Représentation commerciale d'un établissement public étranger",
        "Société par actions simplifiée",
        "Société civile professionnelle de médecins",
        "Société européenne",
        "Société d'exercice libéral à responsabilité limitée à associé unique",
        "Société interprofessionnelle de soins ambulatoires",
        "Société de participations financières de professions libérales à forme de S.A.S.",
        "Société de participations financières de profession libérale de commissaire-priseur judiciaire à responsabilité limitée",
        "Institution régie par les articles L. 141-1 et suivants du Code Monétaire et Financier",
        "Société coopérative d'entreprises à forme anonyme et capital variable",
        "Société coopérative de banque à forme anonyme à capital fixe",
        "Société civile professionnelle de masseurs-kinésithérapeutes",
        "Société civile professionnelle d'administrateurs judiciaires",
        "Société civile professionnelle de commissaires aux comptes",
        "Etablissement public à caractère industriel and commercial",
        "Groupement foncier agricole à capital variable",
        "Société par actions simplifiée à associé unique",
        "Société civile d'exploitation agricole",
        "Union de sociétés coopératives à forme anonyme and capital variable",
        "Union de sociétés coopératives à forme anonyme",
        "Société de participations financières de profession libérale de notaire par actions simplifiée",
        "Société d’économie mixte à opération unique",
        "Société d'investissement à capital variable",
        "Société coopérative d'activité and d'emploi à responsabilité limitée",
        "Société coopérative à responsabilité limitée à capital variable",
        "Société coopérative de production d'HLM à forme anonyme and capital variable",
        "Groupement foncier rural",
        "Mutuelle agricole",
        "Société civile de construction vente",
        "Société d'épargne forestière",
        "Société pluri-professionnelle d'exercice à forme anonyme",
        "Société de participations financières de profession libérale de notaire à responsabilité limitée",
        "Société professionnelle de placement à prépondérance immobilière à capital variable et à forme anonyme",
        "Agence commerciale d'un Etat étranger",
        "Société coopérative de caution mutuelle à capital variable",
        "Société coopérative de crédit",
        "Société coopérative d'intérêt collectif agricole à responsabilité limitée à capital variable",
        "Société civile de placement collectif immobilier",
        "Société anonyme d'HLM",
        "Société en commandite par actions d'un Etat membre de la CE ou partie à l'accord sur l'Espace économique européen",
        "Société civile d'attribution",
        "Société coopérative de construction à forme anonyme",
        "Groupement d'intérêt économique",
        "Etablissement public national",
        "Société pluri-professionnelle d'exercice à responsabilité limitée",
        "Société d'exercice libéral à forme anonyme",
        "Société par actions simplifiée à participation ouvrière",
        "Société en commandite simple",
        "Société de participations financières de profession libérale de vétérinaire par actions simplifiée",
        "Société pluri-professionnelle d'exercice à forme civile",
        "Société coopérative de production à responsabilité limitée à capital variable",
        "Société coopérative and participative à responsabilité limitée",
        "Société coopérative de production à responsabilité limitée",
        "Autre forme juridique;",
        "Société coopérative par actions simplifiée à capital variable",
        "Société coopérative de consommation à forme anonyme",
        "Société coopérative de production à forme anonyme and capital variable",
        "Etablissement d’enseignement supérieur consulaire",
        "Groupement européen d'intérêt économique",
        "Groupement forestier",
        "Société coopérative à responsabilité limitée d'un Etat membre de la CE ou partie à l'accord sur l'Espace économique européen",
        "Société civile professionnelle titulaire d'un office de commissaire-priseur judiciaire",
        "Syndic de copropriété",
        "Société d'exercice libéral par actions simplifiée à associé unique and capital variable",
        "Société d'économie mixte locale à forme anonyme",
        "Société coopérative d'intérêt collectif par actions simplifiée à capital variable",
        "Caisse de crédit agricole mutuel",
        "Société d'exercice libéral à forme anonyme and conseil d'administration",
        "Société à responsabilité limitée à associé unique",
        "Société civile immobilière",
        "Société de participations financières de profession libérale de pharmacien d'officine à responsabilité limitée",
        "Société professionnelle de placement à prépondérance immobilière à capital variable et à forme anonyme sous forme de SAS",
        "Société coopérative d'activité and d'emploi à forme anonyme",
        "Société coopérative agricole à capital variable",
        "Société coopérative artisanale à forme anonyme and capital variable",
        "Société coopérative par actions simplifiée",
        "Société coopérative de commerçants détaillants à forme anonyme",
        "Société coopérative d'entreprises à forme anonyme",
        "Société coopérative à forme anonyme, directoire, à capital variable",
        "Société coopérative de production par actions simplifiée",
        "Société civile constituée en vue de la vente d'immeubles",
        "Société civile foncière",
        "Société civile professionnelle d'architectes",
        "Société civile d'intérêt collectif agricole à capital variable",
        "Société en nom collectif à capital variable",
        "Société nationale",
        "Société de participations d'expertise comptable à responsabilité limitée",
        "Société coopérative artisanale à responsabilité limitée and capital variable",
        "Société coopérative à forme anonyme, directoire and conseil de surveillance",
        "Société coopérative à forme anonyme",
        "Exploitation agricole à responsabilité limitée à capital variable",
        "Groupement d'intérêt économique à capital variable",
        "Société à responsabilité limitée de presse à associé unique",
        "Société en commandite par actions à capital variable",
        "Société civile professionnelle de conseils juridiques",
        "Société civile professionnelle d'huissiers de justice",
        "Société civile professionnelle de mandataires judiciaires",
        "Société d'exercice libéral à responsabilité limitée à associé unique à capital variable",
        "Société de participations financières de profession libérale d'huissier de justice à responsabilité limitée",
        "Société publique locale d'aménagement d'intérêt national",
        "Union d'économie sociale - Société coopérative par actions simplifiée",
        "Société coopérative de crédit à capital variable et responsabilité statutairement limitée",
        "Société à responsabilité limitée d'un Etat membre de la CE ou partie à l'accord sur l'Espace économique européen",
        "Société à responsabilité limitée",
        "Société coopérative d'intérêt collectif à forme anonyme and conseil d'administration",
        "Société coopérative maritime à forme anonyme",
        "Société coopérative maritime",
        "Société civile d'intérêt collectif agricole",
        "Société européenne à actionnaire unique",
        "Société anonyme sportive professionnelle",
        "Société de placement à prépondérance immobilière à capital variable sous la forme SAS",
        "Etablissement public de coopération intercommunale",
        "Société civile de participation",
        "Etablissement public local",
        "Société coopérative artisanale à forme anonyme",
        "Société civile coopérative entre médecins",
        "Société coopérative européenne",
        "Société civile de portefeuille",
        "Société de participations financières de profession libérale d'avocat par actions simplifiée",
        "Union d'économie sociale - Société coopérative à responsabilité limitée and capital variable",
        "Société coopérative maritime à forme anonyme and capital variable",
        "Société civile professionnelle de conseils en propriété industrielle",
        "Société civile professionnelle",
        "Société coopérative de travailleurs à responsabilité limitée",
        "Représentation commerciale d'une collectivité étrangère",
        "Société par actions simplifiée à capital variable",
        "Société de participations financières de profession libérale de pharmacien d'officine par actions simplifiée",
        "Société de participations financières de profession libérale de vétérinaire à responsabilité limitée",
        "Société d'intérêt collectif agricole par actions simplifiée",
        "Etablissement spécial chargé d'administrer les dépôts et les consignations",
        "Société coopérative à responsabilité limitée à capital and personnel variables",
        "Société civile coopérative de consommation",
        "Société civile coopérative",
        "Société coopérative d'intérêt collectif à responsabilité limitée à capital variable",
        "Société coopérative d'intérêt collectif par actions simplifiée",
        "Société coopérative and participative à forme anonyme",
        "Société anonyme d'HLM à directoire and conseil de surveillance",
        "Société en commandite par actions d'un Etat non membre de la CE ou non partie à l'accord sur l'Espace économique européen",
        "Société civile professionnelle d'infirmiers",
        "Société publique locale d'aménagement",
        "Union de sociétés coopératives à responsabilité limitée",
        "Société de caution mutuelle",
        "Caisse d'épargne et de prévoyance",
        "Société coopérative de banque populaire",
        "Société coopérative de consommation à responsabilité limitée",
        "Société coopérative de consommation à forme anonyme and conseil d'administration",
        "Société coopérative de construction à forme anonyme and capital variable",
        "Société coopérative d'intérêt collectif agricole à forme anonyme à capital variable",
        "Etablissement public administratif",
        "Représentation commerciale d'un Etat étranger",
        "Société de réassurance mutuelle",
        "Société anonyme d'HLM à conseil d'administration",
        "Société anonyme à objet sportif",
        "Société à responsabilité limitée de presse à associé unique and capital variable",
        "Société civile d'exploitation aquacole",
        "Société d'économie mixte",
        "Société d'intérêt collectif agricole",
        "Société en nom collectif",
        "Société pluri-professionnelle d'exercice en commandite par actions",
        "Société de placement à prépondérance immobilière",
        "Union de syndicats",
        "Union d'économie sociale - Société coopérative à responsabilité limitée",
        "Société coopérative de consommation à responsabilité limitée and capital variable",
        "Agence commerciale d'une collectivité étrangère",
        "Société à responsabilité limitée d'un Etat non membre de la CE ou non partie à l'accord sur l'Espace économique européen",
        "Société anonyme à directoire and conseil de surveillance",
        "Société coopérative ouvrière de production à responsabilité limitée",
        "Société d'exercice libéral à responsabilité limitée à capital variable",
        "Société d'exercice libéral par actions simplifiée à associé unique",
        "Société d'exercice libéral par actions simplifiée",
        "Société de participations d'expertise comptable",
        "Société de droit étranger",
        "Société à responsabilité limitée à associé unique and capital variable",
        "Société de participations financières de professions libérales",
        "Société coopérative and participative par actions simplifiée",
        "Établissement de crédit maritime mutuel à capital variable",
        "Union d'économie sociale",
        "Association émettant des obligations",
        "Société coopérative de travailleurs à forme anonyme and capital variable",
        "Groupement agricole foncier",
        "Institution de retraite complémentaire",
        "Société à responsabilité limitée de presse à capital variable",
        "Société civile agricole",
        "Société civile d'exploitation viticole",
        "Société civile professionnelle de commissaires-priseurs",
        "Société civile professionnelle de mandataires judiciaires à la liquidation des entreprises",
        "Société en commandite simple à capital variable",
        "Société pluri-professionnelle d'exercice",
        "Société de participations financières de profession libérale d'avocat à responsabilité limitée",
        "Syndicat",
        "Union de coopératives agricoles",
        "Banque coopérative régie par les articles L. 512-85 et suivants du Code Monétaire et Financier",
        "Fonds de dotation",
        "Société civile professionnelle titulaire d'un office de greffier de tribunal de commerce",
        "Société d'exercice libéral à forme anonyme, directoire et conseil de surveillance",
        "Société civile professionnelle de vétérinaires",
        "Société civile professionnelle de notaires",
        "Exploitation agricole à responsabilité limitée",
        "Groupement pastoral",
        "Société anonyme de presse",
        "Régie",
        "Société de placement à prépondérance immobilière à capital variable et à conseil d'administration",
        "Union de coopératives agricoles à capital variable",
        "Union d'économie sociale - Société coopérative par actions simplifiée à capital variable"
    ];

    const [selectedStatus, setSelectedStatus] = useState('');

    const handleFilterChange = (e) => {
        setSelectedStatus(e.target.value);
        onLegalStatusChange(e.target.value);
    };

    return (
        <div>
            <input
                style={{
                    borderRadius: 5,
                    fontSize: 17,
                    padding: 5,
                    fontFamily: 'Poppins',
                    textAlign: 'center',
                    border: '1px solid #5A6ACF',
                    color: '#5A6ACF',
                    backgroundColor: 'white',
                    margin: 7,
                    minWidth: '150%',
                    maxWidth: '150%',
                }}
                type="text"
                placeholder="Filtrer par statut légal"
                value={selectedStatus}
                onChange={handleFilterChange}
                list="legalStatusList" // Lier l'input à la datalist
            />
            <datalist id="legalStatusList">
                {legalStatus.map((status, index) => (
                    <option key={index} value={status}>
                        {status}
                    </option>
                ))}
            </datalist>
        </div>
    );
};

export default LegalStatus;